apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: #namespace_name#
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 32400
  type: NodePort