# PostgreSQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: #namespace_name#
spec:
  serviceName: postgres-service
  selector:
    matchLabels:
      app: postgres-jitsu
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-jitsu
    spec:
      containers:
        - name: postgres
          image: postgres:14
          volumeMounts:
            - name: postgresdb
              mountPath: /var/lib/postgresql/data
              subPath: postgres-data
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-pvc