kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name:  postgres-pvc
  namespace: #namespace_name#
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi