kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name:  minio-pvc
  namespace: minio
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi