kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name:  argos-pvc
  namespace: argos
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi