kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name:  cube-api-schema
  namespace: #namespace_name#
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi