#!/bin/sh
echo "----- Init script enter. Mounting /data -----" | tee /dev/kmsg

DATA_DEV=/dev/$(dmesg | awk '/EXT4-fs/ {print $4}' | tr -d '()' | head -n 1 | sed 's/...$//')p4

resize2fs $DATA_DEV 10G
# yes | parted $ROOT_DEV ---pretend-input-tty resizepart 4 30G
#Mount devices that need to be present for systemd to run below. Otherwise let systemd mount them
mount $DATA_DEV /data

#Run systemd
exec /lib/systemd/systemd "$@"
