apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argos-pvc
  namespace: argos
spec:
  storageClassName: local-storage
  volumeName: argos-pv
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi