apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  namespace: argos
spec:
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/localpv
    type: DirectoryOrCreate
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube