apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: argos
spec:
  storageClassName: local-storage
  volumeName: local-pv
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi