apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: minio
spec:
  storageClassName: local-storage
  volumeName: minio-pvc
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi